services:
  nodejs-mergerr:
    build: .
    container_name: nodejs-mergerr
    volumes:
      - ${TORRENTS_DIR_HOST}:${TORRENTS_DIR}
    restart: unless-stopped
    ports:
      - "${WEB_UI_PORT}:3000"
    env_file:
      - stack.env